---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# childpen

<!-- badges: start -->
<!-- badges: end -->

The goal of childpen is to provide a helper package for estimating child penalties using DID, TD and NTD based methods as discussed in Leventer (2025). 

## Installation

You can install the development version of childpen like so:

```{r installation}
# install.packages("remotes")
# remotes::install_github("dorleventer/childpen")
```

## Example

A basic example of estimating descriptive estimands for several treatment groups:

```{r example}
# library(childpen)
# library(data.table)
# 
# set.seed(1)
# DT <- CJ(id = 1:60, age = 20:26)
# DT[, female := +(id %% 2 == 0)]
# DT[, D := sample(24:28, 60, T)]
# DT[, Y := rnorm(.N, 10 + 0.5*female + 0.1*(age-20))]
# 
# # Single design at d=24, a=25, control dp=26 (pre=1)
# multiple_treatment_group_analysis(
#   DT,
#   treatment_groups = 24:26,
#   periods_post = 1,
#   periods_pre = 2,
#   pre = 1
# )
```
